spring:
  application:
    name: paperless-service


  # JAP
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.default_schema: public

  # DATASOURCE (POSTGRESSSQL)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/memo-service
    username: admin
    password: CCAP@ssw0rd


security:
  oauth2:
    resource:
      user-info-uri: http://10.4.4.111:9100/api/user

    client:
      client-id: trusted-app
      client-secret: XY7kmzoNzl100
      grant-type: client_credentials
      access-token-uri: http://10.4.4.111:9100/api/oauth/token





