# ===============================
# = SERVER
# ===============================
server.port=${port:2026}
server.error.include-stacktrace=never
server.servlet.context-path=/api
endpoints.base.url=${BASE_URL:/gic}
security.mode=${SECURITY_MODE:latest}


  # ===============================
  # = DATA SOURCE
  # ===============================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/gic-service
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.tomcat.test-while-idle=true
spring.datasource.tomcat.validation-query=SELECT 1
spring.datasource.hikari.maximum-pool-size=10

  # ===============================
  # = JPA / HIBERNATE
  # ===============================
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=${DDL_MODE:update}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# = Swagger
# ===============================
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/rest-docs
springdoc.swagger-ui.path=/swagger-ui



  # ===============================
  # = Open Feign
  # ===============================
feign.httpclient.max-connections=10
feign.httpclient.max-connections-per-route=8
feign.client.config.default.connect-timeout=1800000
feign.client.config.default.read-timeout=1800000


camunda.bpm.authorization.enabled=false
base-folder=/files





