spring:
  application:
    name: paperless-service


  # JAP
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.default_schema: public




security:
  oauth2:
    resource:
      user-info-uri: http://10.4.4.111:9100/api/user

    client:
      client-id: trusted-app
      client-secret: XY7kmzoNzl100
      grant-type: client_credentials
      access-token-uri: http://10.4.4.111:9100/api/oauth/token





